### ISSUE TITLE
Create Interview returns 401

### ISSUE THREAD

**Issue by utkarsha2016** [Microsoft/skype-interviews-samples#3]
I tried using multiple api keys and secrets but I get 401 every time. Not sure if Rest API is not working or its the client issue

**Comment by nimal-work** [comment]
Hello,
what language sample were you using? Can you share your code sample and/or requests which were made and failing?

In case you are not confortable sharing this info here, you can send it to our email skypeinterviewsfeedb@microsoft.com

**Comment by nimal-work** [comment]
I've checked csharp sample and I found an error there so I guess that was the sdk failing so I will resolve this issue as fixed with my pr

**Comment by utkarsha2016** [comment]
Thanks. It was the CSharp example that was failing for me
